name: playtomic-exercise-wallet-service

services:
  mongodb:
    image: mongo:8.0
    container_name: playtomic-exercise-wallet-service-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local